### ISSUE TITLE
Crash please help me fix 

### ISSUE THREAD

**Issue by OskarRB051007** [abused/SuperOres#14]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  HCASM (HammerCore-1.12.2-2.0.5.5.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 11/9/19 4:45 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from SuperOres (superores)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at net.minecraft.util.NonNullList.get(SourceFile:44)
	at abused_master.superores.blocks.BlockOreBase.<init>(BlockOreBase.java:66)
	at abused_master.superores.registry.ModResources.register(ModResources.java:32)
	at abused_master.superores.proxy.CommonProxy.preInit(CommonProxy.java:22)
	at abused_master.superores.proxy.ClientProxy.preInit(ClientProxy.java:23)
	at abused_master.superores.SuperOres.preinit(SuperOres.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1794414800 bytes (1711 MB) / 2550136832 bytes (2432 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_F4 28 mods loaded, 28 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                       | Version                 | Source                                        | Signature                                |
	|:----- |:------------------------ |:----------------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                | 1.12.2                  | minecraft.jar                                 | None                                     |
	| LCH   | mcp                      | 9.42                    | minecraft.jar                                 | None                                     |
	| LCH   | FML                      | 8.0.99.99               | forge-1.12.2-14.23.5.2838.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                    | 14.23.5.2838            | forge-1.12.2-14.23.5.2838.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | codechickenlib           | 3.2.3.358               | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | ancientwarfare           | 1.12.2-2.7.0.772        | ancientwarfare-1.12.2-2.7.0.772.jar           | None                                     |
	| LCH   | ancientwarfarestructure  | 1.12.2-2.7.0.772        | ancientwarfare-1.12.2-2.7.0.772.jar           | None                                     |
	| LCH   | ancientwarfarevehicle    | 1.12.2-2.7.0.772        | ancientwarfare-1.12.2-2.7.0.772.jar           | None                                     |
	| LCH   | ancientwarfarenpc        | 1.12.2-2.7.0.772        | ancientwarfare-1.12.2-2.7.0.772.jar           | None                                     |
	| LCH   | buildcraftlib            | 7.99.24.1               | BuildCraft-Core-1.12.2.jar                    | None                                     |
	| LCH   | buildcraftcore           | 7.99.24.1               | BuildCraft-Core-1.12.2.jar                    | None                                     |
	| LCH   | ancientwarfareautomation | 1.12.2-2.7.0.772        | ancientwarfare-1.12.2-2.7.0.772.jar           | None                                     |
	| LCH   | bluepower                | 0.3.38                  | Blue-Power-Mod-1.12.2.jar                     | None                                     |
	| LCH   | buildcrafttransport      | 7.99.24.1               | BuildCraft-Transport-Module-1.12.2.jar        | None                                     |
	| LCH   | compactstorage           | 3.1                     | CompactStorage-3.1-12.jar                     | None                                     |
	| LCH   | hammercore               | 2.0.5.5                 | HammerCore-1.12.2-2.0.5.5.jar                 | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCH   | jei                      | 4.15.0.291              | jei_1.12.2-4.15.0.291.jar                     | None                                     |
	| LCH   | projecte                 | 1.12.2-PE1.4.1          | ProjectE-1.12.2-PE1.4.1.jar                   | None                                     |
	| LCH   | expequiv                 | 13r                     | ExpandedEquivalence-1.12.2-13r.jar            | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCH   | umm3185118519            | alpha 1.1.1 - MC 1.12.2 | Extended-Items-and-Ores-1.12.2.jar            | None                                     |
	| LCH   | extrautils2              | 1.0                     | Extra-Utilities-Mod-1.12.2.jar                | None                                     |
	| LCH   | ironbackpacks            | 1.12.2-3.0.8-12         | IronBackpacks-1.12.2-3.0.8-12.jar             | None                                     |
	| LCH   | orespawn                 | 3.3.0                   | MMD-OreSpawn-1.12.2.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | projectex                | 1.2.0.39                | ProjectEX-1.2.0.39.jar                        | None                                     |
	| LCH   | veinminer                | 0.38.2                  | VeinMiner-1.12-0.38.2.647+b31535a.jar         | None                                     |
	| LCH   | veinminermodsupport      | 0.38.2                  | VeinMiner-1.12-0.38.2.647+b31535a.jar         | None                                     |
	| LCH   | xaerominimap             | 1.18.8                  | Xaeros_Minimap_1.18.8_Forge_1.12.jar          | None                                     |
	| LCE   | superores                | 1.9.0_1.12              | superores-1.9.0-1.12.jar                      | None                                     |

	Loaded coremods (and transformers): 
HCASM (HammerCore-1.12.2-2.0.5.5.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
	GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.4459' Renderer: 'Intel(R) HD Graphics 3000'
	HammerCore Debug Information: 
Dependent Mods:
    -Expanded Equivalence (expequiv) @13r

	OptiFine Version: OptiFine_1.12.2_HD_U_F4
	OptiFine Build: 20191023-234904
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.1.0 - Build 9.17.10.4459
	OpenGlRenderer: Intel(R) HD Graphics 3000
	OpenGlVendor: Intel
	CpuCount: 4

please help me

**Comment by Linksvix99** [comment]
I've actually had the same crash occur multiple times, and the only mods that you used that I also used was JEI and Iron Backpacks.
[crash-2019-12-23_09.15.40-client.txt](https://github.com/abused/SuperOres/files/3995417/crash-2019-12-23_09.15.40-client.txt)
