### ISSUE TITLE
[Bug]: 1.12.2 Crash

### ISSUE THREAD

**Issue by CJCon** [abused/SuperOres#21]
### Bug Description

Crashes on startup. I'm assuming it's not playing well with another mod but I can't figure out which.
Using SuperOres 1.9.0-1.12.2

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.2.7.4.jar)
  SoManyEnchantments ASM (SoManyEnchantments-0.5.5.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  ForgelinPlugin (Forgelin-1.8.3.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  CreativePatchingLoader (CreativeCore_v1.10.71_mc1.12.2.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50.jar)
  LogisticsPipesCoreLoader (logisticspipes-0.10.4.49.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  DLFMLCorePlugin (DynamicLights-1.12.2.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.3.3.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 5/30/24 7:18 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from SuperOres (superores)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at net.minecraft.util.NonNullList.get(SourceFile:44)
	at abused_master.superores.blocks.BlockOreBase.<init>(BlockOreBase.java:66)
	at abused_master.superores.registry.ModResources.register(ModResources.java:31)
	at abused_master.superores.proxy.CommonProxy.preInit(CommonProxy.java:22)
	at abused_master.superores.proxy.ClientProxy.preInit(ClientProxy.java:23)
	at abused_master.superores.SuperOres.preinit(SuperOres.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2024697240 bytes (1930 MB) / 3407872000 bytes (3250 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx4096m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 166 mods loaded, 166 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                          | Version                  | Source                                         | Signature                                |
	|:----- |:--------------------------- |:------------------------ |:---------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                   | 1.12.2                   | minecraft.jar                                  | None                                     |
	| LCH   | mcp                         | 9.42                     | minecraft.jar                                  | None                                     |
	| LCH   | FML                         | 8.0.99.99                | forge-1.12.2-14.23.5.2859-universal.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                       | 14.23.5.2859             | forge-1.12.2-14.23.5.2859-universal.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | creativecoredummy           | 1.0.0                    | minecraft.jar                                  | None                                     |
	| LCH   | openmodscore                | 0.12.2                   | minecraft.jar                                  | None                                     |
	| LCH   | movillages                  | 1.5.4                    | [1.12]MoVillages-1.5.4.jar                     | None                                     |
	| LCH   | deconstruction              | 3.0.4                    | [MC1.12.2]DeconTable-3.0.4.jar                 | None                                     |
	| LCH   | orbis-lib                   | 0.2.0                    | orbis-lib-1.12.2-0.2.0+build411.jar            | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LCH   | aether                      | 0.3.0                    | aether_ii-1.12.2-0.3.0+build411-universal.jar  | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LCH   | architecturecraft           | @VERSION@                | architecturecraft-1.12-3.108.jar               | None                                     |
	| LCH   | baubles                     | 1.5.2                    | Baubles-1.12-1.5.2.jar                         | None                                     |
	| LCH   | artifacts                   | 1.12.2-1.2.4             | artifacts-1.12.2-1.2.4.jar                     | None                                     |
	| LCH   | backpack                    | 3.0.2                    | backpack-3.0.2-1.12.2.jar                      | None                                     |
	| LCH   | crafttweaker                | 4.1.20                   | CraftTweaker2-1.12-4.1.20.699.jar              | None                                     |
	| LCH   | jei                         | 4.16.1.1012              | jei_1.12.2-4.16.1.1012.jar                     | None                                     |
	| LCH   | base                        | 3.14.0                   | base-1.12.2-3.14.0.jar                         | None                                     |
	| LCH   | battletowers                | 1.6.5                    | BattleTowers-1.12.2.jar                        | None                                     |
	| LCH   | betterbedrockgen            | 6.0.2                    | BetterBedrockGenerator-1.12-6.1.1.jar          | None                                     |
	| LCH   | bettercaves                 | 1.12.2                   | bettercaves-1.12.2-2.0.4.jar                   | None                                     |
	| LCH   | forgelin                    | 1.8.3                    | Forgelin-1.8.3.jar                             | None                                     |
	| LCH   | betterfoliage               | 2.3.2                    | BetterFoliage-MC1.12-2.3.3.jar                 | None                                     |
	| LCH   | bettermineshafts            | 1.12.2-2.2.1             | BetterMineshaftsForge-1.12.2-2.2.1.jar         | None                                     |
	| LCH   | bibliocraft                 | 2.4.6                    | BiblioCraft[v2.4.6][MC1.12.2].jar              | None                                     |
	| LCH   | biomesoplenty               | 7.0.1.2445               | BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar  | None                                     |
	| LCH   | blockcraftery               | 1.12.2-1.3.1             | blockcraftery-1.12.2-1.3.1.jar                 | None                                     |
	| LCH   | bookshelf                   | 2.3.590                  | Bookshelf-1.12.2-2.3.590.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | bowinfinityfix              | rv5.1                    | BowInfinityFix-1.12.2-rv5.1.jar                | None                                     |
	| LCH   | buildcraftlib               | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                   | None                                     |
	| LCH   | buildcraftcore              | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                   | None                                     |
	| LCH   | buildcraftbuilders          | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                   | None                                     |
	| LCH   | buildcrafttransport         | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                   | None                                     |
	| LCH   | buildcraftsilicon           | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                   | None                                     |
	| LCH   | ic2                         | 2.8.222-ex112            | industrialcraft-2-2.8.222-ex112.jar            | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCH   | buildcraftcompat            | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                   | None                                     |
	| LCH   | buildcraftenergy            | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                   | None                                     |
	| LCH   | buildcraftfactory           | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                   | None                                     |
	| LCH   | buildcraftrobotics          | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                   | None                                     |
	| LCH   | capsule                     | 1.12.2-3.4.76            | Capsule-1.12.2-3.4.76.jar                      | None                                     |
	| LCH   | gamestages                  | 2.0.123                  | GameStages-1.12.2-2.0.123.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | carryon                     | 1.12.3                   | carryon-1.12.2-1.12.7.23.jar                   | None                                     |
	| LCH   | ceilingtorch                | v1.3.1                   | ceilingtorch-1.12.2-v1.3.1.jar                 | None                                     |
	| LCH   | chameleon                   | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                       | None                                     |
	| LCH   | champions                   | 1.12.2-1.0.11.10         | champions-1.12.2-1.0.11.10.jar                 | b33d2c8df492beff56d1bbbc92da49b8ab7345a1 |
	| LCH   | chancecubes                 | 1.12.2-5.0.2.385         | ChanceCubes-1.12.2-5.0.2.385.jar               | None                                     |
	| LCH   | chesttransporter            | 2.8.8                    | ChestTransporter-1.12.2-2.8.8.jar              | None                                     |
	| LCH   | ctm                         | MC1.12.2-1.0.2.31        | CTM-MC1.12.2-1.0.2.31.jar                      | None                                     |
	| LCH   | chisel                      | MC1.12.2-1.0.2.45        | Chisel-MC1.12.2-1.0.2.45.jar                   | None                                     |
	| LCH   | chiselsandbits              | 14.33                    | chiselsandbits-14.33.jar                       | None                                     |
	| LCH   | codechickenlib              | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | comforts                    | 1.4.1.3                  | comforts-1.12.2-1.4.1.3.jar                    | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCH   | mantle                      | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                       | None                                     |
	| LCH   | thaumcraft                  | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar               | None                                     |
	| LCH   | twilightforest              | 3.11.1021                | twilightforest-1.12.2-3.11.1021-universal.jar  | None                                     |
	| LCH   | tconstruct                  | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar               | None                                     |
	| LCH   | contenttweaker              | 1.12.2-4.10.0            | ContentTweaker-1.12.2-4.10.0.jar               | None                                     |
	| LCH   | conarm                      | 1.2.5.10                 | conarm-1.12.2-1.2.5.10.jar                     | b33d2c8df492beff56d1bbbc92da49b8ab7345a1 |
	| LCH   | craftabletotemofundying     | 1.0.0                    | CraftableTotemOfUndying-1.12.2-1.0.0.jar       | None                                     |
	| LCH   | eleccore                    | 1.9.453                  | ElecCore-1.12.2-1.9.453.jar                    | None                                     |
	| LCH   | craftingtableiv             | 1.12.2-1.5.123           | CraftingTableIV-1.12.2-1.5.123.jar             | None                                     |
	| LCH   | ctgui                       | 1.0.0                    | CraftTweaker2-1.12-4.1.20.699.jar              | None                                     |
	| LCH   | crafttweakerjei             | 2.0.3                    | CraftTweaker2-1.12-4.1.20.699.jar              | None                                     |
	| LCH   | creativecore                | 1.10.0                   | CreativeCore_v1.10.71_mc1.12.2.jar             | None                                     |
	| LCH   | cucumber                    | 1.1.3                    | Cucumber-1.12.2-1.1.3.jar                      | None                                     |
	| LCH   | cxlibrary                   | 1.6.1                    | cxlibrary-1.12.1-1.6.1.jar                     | None                                     |
	| LCH   | cyclicmagic                 | 1.20.12                  | Cyclic-1.12.2-1.20.14.jar                      | 0e5cb559be7d03f3fc18b8cba547d663e25f28af |
	| LCH   | waila                       | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                    | None                                     |
	| LCH   | darkutils                   | 1.8.230                  | DarkUtils-1.12.2-1.8.230.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | dldungeonsjbg               | 1.14.12                  | DoomlikeDungeons-1.14.12-MC1.12.2.jar          | None                                     |
	| LCH   | mocreatures                 | 12.4.2                   | DrZharks-MoCreatures-Extended-12.4.2.jar       | None                                     |
	| LCH   | dungeontactics              | DT-0.16.9                | DungeonTactics-1.12.2-0.16.9.jar               | None                                     |
	| LCH   | durabilityshow              | 5.0.0                    | Durability Show-1.12-5.0.0.jar                 | None                                     |
	| LCH   | dynamiclights               | 1.4.9                    | DynamicLights-1.12.2.jar                       | None                                     |
	| LCH   | dynamiclights_onfire        | 1.0.7                    | DynamicLights-1.12.2.jar                       | None                                     |
	| LCH   | dynamiclights_creepers      | 1.0.6                    | DynamicLights-1.12.2.jar                       | None                                     |
	| LCH   | dynamiclights_dropitems     | 1.1.0                    | DynamicLights-1.12.2.jar                       | None                                     |
	| LCH   | dynamiclights_entityclasses | 1.0.1                    | DynamicLights-1.12.2.jar                       | None                                     |
	| LCH   | dynamiclights_mobequipment  | 1.1.0                    | DynamicLights-1.12.2.jar                       | None                                     |
	| LCH   | dynamiclights_flamearrows   | 1.0.1                    | DynamicLights-1.12.2.jar                       | None                                     |
	| LCH   | dynamiclights_floodlights   | 1.0.3                    | DynamicLights-1.12.2.jar                       | None                                     |
	| LCH   | dynamiclights_otherplayers  | 1.0.9                    | DynamicLights-1.12.2.jar                       | None                                     |
	| LCH   | dynamiclights_theplayer     | 1.1.3                    | DynamicLights-1.12.2.jar                       | None                                     |
	| LCH   | dynamictrees                | 1.12.2-0.9.29            | DynamicTrees-1.12.2-0.9.29.jar                 | None                                     |
	| LCH   | dynamictreesbop             | 1.12.2-9999.9999.9999z   | DynamicTreesBOP-1.12.2-1.5.2.jar               | None                                     |
	| LCH   | dynamictreesttf             | 1.12.2-1.2.3             | dynamictreesTheTwilightForest-1.12.2-1.2.3.jar | None                                     |
	| LCH   | elevatorid                  | 1.3.14                   | ElevatorMod-1.12.2-1.3.14.jar                  | None                                     |
	| LCH   | eplus                       | 5.0.176                  | EnchantingPlus-1.12.2-5.0.176.jar              | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | enchdesc                    | 1.1.15                   | EnchantmentDescriptions-1.12.2-1.1.15.jar      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | enhancedarmaments           | 1.3.21                   | enhancedarmaments-1.3.21.jar                   | None                                     |
	| LCH   | extrautils2                 | 1.0                      | extrautils2-1.12-1.9.9.jar                     | None                                     |
	| LCH   | fbp                         | 2.4.1                    | FancyBlockParticles-1.12.x-2.4.1.jar           | None                                     |
	| LCH   | fenceoverhaul               | 1.3.4                    | FenceOverhaul-1.3.4.jar                        | None                                     |
	| LCH   | geckolib3                   | 3.0.30                   | geckolib-forge-1.12.2-3.0.31.jar               | None                                     |
	| LCH   | grapplemod                  | 1.12.2-v13               | grappling_hook_mod-1.12.2-v13.jar              | None                                     |
	| LCH   | gravestone                  | 1.10.3                   | gravestone-1.10.3.jar                          | None                                     |
	| LCH   | llibrary                    | 1.7.20                   | llibrary-1.7.20-1.12.2.jar                     | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | iceandfire                  | 1.9.1                    | iceandfire-1.9.1-1.12.2.jar                    | None                                     |
	| LCH   | ichunutil                   | 7.2.2                    | iChunUtil-1.12.2-7.2.2.jar                     | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCH   | infernalmobs                | 1.7.6                    | InfernalMobs-1.12.2.jar                        | None                                     |
	| LCH   | inventorypets               | 2.0.15                   | inventorypets-1.12-2.0.15.jar                  | None                                     |
	| LCH   | inventorytweaks             | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                       | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCH   | ironchest                   | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                | None                                     |
	| LCH   | jeiintegration              | 1.6.0                    | jeiintegration_1.12.2-1.6.0.jar                | None                                     |
	| LCH   | journeymap                  | 1.12.2-5.7.1p3           | journeymap-1.12.2-5.7.1p3.jar                  | None                                     |
	| LCH   | jrftl                       | 1.1                      | JRFTL[1.12.2]-1.1.jar                          | None                                     |
	| LCH   | jecalculation               | 1.12.2-3.2.7             | JustEnoughCalculation-1.12.2-3.2.7.jar         | None                                     |
	| LCH   | logisticspipes              | 0.10.4.49                | logisticspipes-0.10.4.49.jar                   | e0c86912b2f7cc0cc646ad57799574aea43dbd45 |
	| LCH   | longfallboots               | 1.2.1a                   | longfallboots-1.2.1b.jar                       | None                                     |
	| LCH   | lootbags                    | 2.5.8.5                  | LootBags-1.12.2-2.5.8.5.jar                    | None                                     |
	| LCH   | magicalcrops                | 1.0.1                    | magicalcrops-1.0.2-MC-1.12.jar                 | None                                     |
	| LCH   | mahoutsukai                 | 1.12.2-v1.19.55          | mahoutsukai-1.12.2-v1.19.55.jar                | None                                     |
	| LCH   | malisiscore                 | 1.12.2-6.5.1-SNAPSHOT    | malisiscore-1.12.2-6.5.1.jar                   | None                                     |
	| LCH   | malisisblocks               | 1.12.2-6.1.0             | malisisblocks-1.12.2-6.1.0.jar                 | None                                     |
	| LCH   | malisisdoors                | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                  | None                                     |
	| LCH   | malisisswitches             | 1.12.2-5.1.0             | malisisswitches-1.12.2-5.1.0.jar               | None                                     |
	| LCH   | mcjtylib_ng                 | 3.5.4                    | mcjtylib-1.12-3.5.4.jar                        | None                                     |
	| LCH   | mcwdoors                    | 1.3                      | mcw-doors-1.0.3-mc1.12.2.jar                   | None                                     |
	| LCH   | mcwwindows                  | 1.0                      | mcw-windows-1.0.0-mc1.12.2.jar                 | None                                     |
	| LCH   | megaloot                    | 0.2.40                   | megaloot-1.12.2-0.2.40.jar                     | None                                     |
	| LCH   | testdummy                   | 1.12                     | MmmMmmMmmMmm-1.12-1.14.jar                     | None                                     |
	| LCH   | mobamputation               | 7.0.0                    | MobAmputation-1.12.2-7.0.1.jar                 | None                                     |
	| LCH   | mob_grinding_utils          | 0.3.13                   | MobGrindingUtils-0.3.13.jar                    | None                                     |
	| LCH   | morefurnaces                | 1.10.5                   | MoreFurnaces-1.12.2-1.10.6.jar                 | None                                     |
	| LCH   | morph                       | 7.2.0                    | Morph-1.12.2-7.2.1.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCH   | mowziesmobs                 | 1.5.8                    | mowziesmobs_1.12.2_1.5.8.jar                   | None                                     |
	| LCH   | mysticalagriculture         | 1.7.5                    | MysticalAgriculture-1.12.2-1.7.5.jar           | None                                     |
	| LCH   | mysticalagradditions        | 1.3.2                    | MysticalAgradditions-1.12.2-1.3.2.jar          | None                                     |
	| LCH   | naturescompass              | 1.8.5                    | NaturesCompass-1.12.2-1.8.5.jar                | None                                     |
	| LCH   | notenoughwands              | 1.8.1                    | notenoughwands-1.12-1.8.1.jar                  | None                                     |
	| LCH   | openmods                    | 0.12.2                   | OpenModsLib-1.12.2-0.12.2.jar                  | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCH   | openblocks                  | 1.8.1                    | OpenBlocks-1.12.2-1.8.1.jar                    | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCH   | oreberries                  | 0.5.0                    | oreberries-1.12.x-0.5.0.jar                    | None                                     |
	| LCH   | patchouli                   | 1.0-23.6                 | Patchouli-1.0-23.6.jar                         | None                                     |
	| LCH   | plonk                       | 10.0.4                   | plonk-1.12.2-10.0.4.jar                        | None                                     |
	| LCH   | portablecraftingtable       | 1.1.4                    | PortableCraftingTable-1.12.2-1.1.4.jar         | None                                     |
	| LCH   | portalgun                   | 7.1.0                    | PortalGun-1.12.2-7.1.0.jar                     | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCH   | railcraft                   | 12.1.0-beta-8            | railcraft-12.1.0-beta-8.jar                    | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCH   | randomthings                | 4.2.7.4                  | RandomThings-MC1.12.2-4.2.7.4.jar              | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCH   | refinedrelocation           | 4.2.37                   | RefinedRelocation_1.12.2-4.2.37.jar            | None                                     |
	| LCH   | refinedstorage              | 1.6.16                   | refinedstorage-1.6.16.jar                      | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCH   | additionalstructures        | 2.5.0                    | Rex's-AdditionalStructures-1.12.x(v.2.5.0).jar | None                                     |
	| LCH   | roguelike                   | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar             | None                                     |
	| LCH   | ruins                       | 17.2                     | Ruins-1.12.2.jar                               | None                                     |
	| LCH   | storagenetwork              | 1.8.3                    | SimpleStorageNetwork-1.12.2-1.8.3.jar          | 0e5cb559be7d03f3fc18b8cba547d663e25f28af |
	| LCH   | lteleporters                | 1.12.2-3.0.2             | simpleteleporters-1.12.2-3.0.2.jar             | None                                     |
	| LCH   | simplybackpacks             | 1.4.9                    | simplybackpacks-1.4.9.jar                      | None                                     |
	| LCH   | simplylight                 | 1.12.2-0.8.7             | simplylight-1.12.2-0.8.7.jar                   | None                                     |
	| LCH   | snad                        | 1.12.1-1.7.09.16a        | Snad-1.12.1-1.7.09.16a.jar                     | None                                     |
	| LCH   | somanyenchantments          | 0.5.5                    | SoManyEnchantments-0.5.5.jar                   | None                                     |
	| LCH   | storagedrawers              | 5.5.0                    | StorageDrawers-1.12.2-5.5.0.jar                | None                                     |
	| LCH   | sync                        | 7.1.0                    | Sync-1.12.2-7.1.0.jar                          | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCH   | tinkersjei                  | 1.2                      | tinkersjei-1.2.jar                             | None                                     |
	| LCH   | tinkertoolleveling          | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar            | None                                     |
	| LCH   | torchmaster                 | 1.8.5.0                  | torchmaster_1.12.2-1.8.5.0.jar                 | None                                     |
	| LCH   | torchslabmod                | v1.5.2                   | torchslabmod-1.12.2-v1.5.2.jar                 | None                                     |
	| LCH   | treechopper                 | 1.2.4                    | TreeChopper-1.12.2-1.2.4.jar                   | None                                     |
	| LCH   | veinminer                   | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar          | None                                     |
	| LCH   | veinminermodsupport         | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar          | None                                     |
	| LCH   | waystones                   | 4.1.0                    | Waystones_1.12.2-4.1.0.jar                     | None                                     |
	| LCH   | xtones                      | 1.2.2                    | Xtones-1.2.2.jar                               | None                                     |
	| LCH   | phosphor-lighting           | 1.12.2-0.2.6             | phosphor-1.12.2-0.2.6+build50.jar              | f0387d288626cc2d937daa504e74af570c52a2f1 |
	| LCH   | ropebridge                  | 2.0.5                    | RopeBridge-1.12.2-2.2.1.jar                    | None                                     |
	| LCH   | corail_pillar               | 4.2.1                    | corail_pillar-4.2.1-1.12.jar                   | None                                     |
	| LCH   | eleccoreloader              | 1.9.453                  | ElecCore-1.12.2-1.9.453.jar                    | None                                     |
	| LCH   | mysticallib                 | 1.12.2-1.13.0            | mysticallib-1.12.2-1.13.0.jar                  | None                                     |
	| LCE   | superores                   | 1.9.0_1.12               | superores-1.9.0-1.12.jar                       | None                                     |

	Loaded coremods (and transformers): 
MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  
LoadingPlugin (RandomThings-MC1.12.2-4.2.7.4.jar)
  lumien.randomthings.asm.ClassTransformer
SoManyEnchantments ASM (SoManyEnchantments-0.5.5.jar)
  com.Shultrea.Rin.Transformer.SMEASM
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  cubex2.cxlibrary.CoreModTransformer
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
ForgelinPlugin (Forgelin-1.8.3.jar)
  
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
CreativePatchingLoader (CreativeCore_v1.10.71_mc1.12.2.jar)
  
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50.jar)
  
LogisticsPipesCoreLoader (logisticspipes-0.10.4.49.jar)
  logisticspipes.asm.LogisticsClassTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
DLFMLCorePlugin (DynamicLights-1.12.2.jar)
  atomicstryker.dynamiclights.common.DLTransformer
BetterFoliageLoader (BetterFoliage-MC1.12-2.3.3.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 552.44' Renderer: 'NVIDIA GeForce GTX 1080/PCIe/SSE2'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Patchouli open book context: n/a

### Version

1.9.0

### Mod Loader Version

1.12.2

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by a7392** [comment]
randomthings,I used to add it successfully, but then the launch kept crashing
